### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/coherent.deps#1]
For some reason, the tests are failing on Windows:

```python-traceback
_______________ [doctest] coherent.deps.imports.Import.builtin ________________
048 
049         Is this import built-in (part of the stdandard library)?
050 
051         An import is built-in if it's top-level name is importable
052         without any third-party packages.
053 
054         >>> Import('requests').builtin()
UNEXPECTED EXCEPTION: OSError(22, 'The parameter is incorrect', None, 87, None)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\doctest.py", line 1334, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest coherent.deps.imports.Import.builtin[0]>", line 1, in <module>
  File "D:\a\coherent.deps\coherent.deps\imports.py", line 63, in builtin
    return self._check_builtin(self.split('.')[0])
  File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-run-4ie898z4\jaraco\context\__init__.py", line 285, in wrapper
    func(*args, **kwargs)
  File "D:\a\coherent.deps\coherent.deps\imports.py", line 72, in _check_builtin
    subprocess.check_call(cmd, env={}, stderr=subprocess.DEVNULL)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect
D:\a\coherent.deps\coherent.deps\imports.py:54: UnexpectedException
```

**Comment by jaraco** [comment]
When I run the tests on my windows machine, the tests pass, but then the run fails during teardown with an error in coh.test.

**Comment by jaraco** [comment]
Since the tests are passing on my machine, I'm now suspicious that `subprocess.check_call(stderr=subprocess.DEVNULL)` is not allowed on GitHub actions.

Shame on Windows for that terrible error message.

**Comment by jaraco** [comment]
I'm seeing other users [have a similar issue](https://stackoverflow.com/questions/73999995/createprocess-from-python-results-in-oserror-winerror-87-the-parameter-is-in) relating to the extension they added to their executable, unrelated to stderr or devnull.

**Comment by jaraco** [comment]
Here's [another issue with that error](https://stackoverflow.com/questions/66908593/oserror-winerror-87-the-parameter-is-incorrect) implicating the environment variables. Now this feels familiar. I seem to recall that in some environments, it's unsafe to remove all environment variables.

**Comment by jaraco** [comment]
https://github.com/thonny/thonny/issues/2509 looks related, but it's unclear to me [which of the changes in the fixed release](https://github.com/thonny/thonny/compare/v4.0.1..v4.0.2) are implicated. Maybe the `executable=` parameter to the subprocess call?

**Comment by jaraco** [comment]
The value of `sys.executable` (`C:\Program Files (x86)\pipx\.cache\b92d1f6b10f4bb5\Scripts\python.exe`) looks perfectly reasonable, so the issue must be the stderr or env parameters.

**Comment by jaraco** [comment]
Removing the `env={}` allows that test to run but fail:

```
054         >>> Import('requests').builtin()
Expected:
    False
Got:
    True
```

So probably the issue pertains to some missing but required variable.

**Comment by jaraco** [comment]
Simply removing PYTHONPATH from the env allows the test to pass.

I've found https://github.com/python/cpython/issues/120836, which addresses the underlying issue more directly.
